# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Set up MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        image-version: latest
        port: 27017
    - name: Set up JDK 16 for Collar API
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Checkout Pounce
      uses: actions/checkout@v2
      with:
        repository: collarmc/pounce
        path: pounce
    - name: Build Pounce
      working-directory: pounce
      run: mvn -B install --file pom.xml -Dmaven.test.skip=true
    - name: Checkout Collar API
      uses: actions/checkout@v2
      with:
        repository: collarmc/collar
        path: collar
    - name: Build Collar API
      working-directory: collar
      run: mvn -B install --file pom.xml -Dmaven.test.skip=true
    - name: Set up JDK 8 for Collar mod
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Checkout Collar mod
      uses: actions/checkout@v2
      with:
        repository: collarmc/collar-mod
        path: collar-mod
    - name: Build Collar Mod
      working-directory: collar-mod
      run: ./gradlew clean build
